# Generated by Django 2.1.2 on 2020-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scqf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='id',
        ),
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
